package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Contienen generated by hbm2java
 */
public class Contienen  implements java.io.Serializable {


     private ContienenId id;

    public Contienen() {
    }

    public Contienen(ContienenId id) {
       this.id = id;
    }
   
    public ContienenId getId() {
        return this.id;
    }
    
    public void setId(ContienenId id) {
        this.id = id;
    }




}


