package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * ContienenId generated by hbm2java
 */
public class ContienenId  implements java.io.Serializable {


     private int examenFinalIdExamenFinal;
     private int preguntasIdPregunta;

    public ContienenId() {
    }

    public ContienenId(int examenFinalIdExamenFinal, int preguntasIdPregunta) {
       this.examenFinalIdExamenFinal = examenFinalIdExamenFinal;
       this.preguntasIdPregunta = preguntasIdPregunta;
    }
   
    public int getExamenFinalIdExamenFinal() {
        return this.examenFinalIdExamenFinal;
    }
    
    public void setExamenFinalIdExamenFinal(int examenFinalIdExamenFinal) {
        this.examenFinalIdExamenFinal = examenFinalIdExamenFinal;
    }
    public int getPreguntasIdPregunta() {
        return this.preguntasIdPregunta;
    }
    
    public void setPreguntasIdPregunta(int preguntasIdPregunta) {
        this.preguntasIdPregunta = preguntasIdPregunta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContienenId) ) return false;
		 ContienenId castOther = ( ContienenId ) other; 
         
		 return (this.getExamenFinalIdExamenFinal()==castOther.getExamenFinalIdExamenFinal())
 && (this.getPreguntasIdPregunta()==castOther.getPreguntasIdPregunta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getExamenFinalIdExamenFinal();
         result = 37 * result + this.getPreguntasIdPregunta();
         return result;
   }   


}


