package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Estudian generated by hbm2java
 */
public class Estudian  implements java.io.Serializable {


     private int idEstudia;

    public Estudian() {
    }

    public Estudian(int idEstudia) {
       this.idEstudia = idEstudia;
    }
   
    public int getIdEstudia() {
        return this.idEstudia;
    }
    
    public void setIdEstudia(int idEstudia) {
        this.idEstudia = idEstudia;
    }




}


