package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * ExamenFinal generated by hbm2java
 */
public class ExamenFinal  implements java.io.Serializable {


     private int idExamenFinal;
     private int puntaje;

    public ExamenFinal() {
    }

    public ExamenFinal(int idExamenFinal, int puntaje) {
       this.idExamenFinal = idExamenFinal;
       this.puntaje = puntaje;
    }
   
    public int getIdExamenFinal() {
        return this.idExamenFinal;
    }
    
    public void setIdExamenFinal(int idExamenFinal) {
        this.idExamenFinal = idExamenFinal;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }




}


