package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * GestionanId generated by hbm2java
 */
public class GestionanId  implements java.io.Serializable {


     private int usuariosIdUsuario;
     private int preguntasIdPregunta;

    public GestionanId() {
    }

    public GestionanId(int usuariosIdUsuario, int preguntasIdPregunta) {
       this.usuariosIdUsuario = usuariosIdUsuario;
       this.preguntasIdPregunta = preguntasIdPregunta;
    }
   
    public int getUsuariosIdUsuario() {
        return this.usuariosIdUsuario;
    }
    
    public void setUsuariosIdUsuario(int usuariosIdUsuario) {
        this.usuariosIdUsuario = usuariosIdUsuario;
    }
    public int getPreguntasIdPregunta() {
        return this.preguntasIdPregunta;
    }
    
    public void setPreguntasIdPregunta(int preguntasIdPregunta) {
        this.preguntasIdPregunta = preguntasIdPregunta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GestionanId) ) return false;
		 GestionanId castOther = ( GestionanId ) other; 
         
		 return (this.getUsuariosIdUsuario()==castOther.getUsuariosIdUsuario())
 && (this.getPreguntasIdPregunta()==castOther.getPreguntasIdPregunta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuariosIdUsuario();
         result = 37 * result + this.getPreguntasIdPregunta();
         return result;
   }   


}


