package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Gestionan generated by hbm2java
 */
public class Gestionan  implements java.io.Serializable {


     private GestionanId id;

    public Gestionan() {
    }

    public Gestionan(GestionanId id) {
       this.id = id;
    }
   
    public GestionanId getId() {
        return this.id;
    }
    
    public void setId(GestionanId id) {
        this.id = id;
    }




}


