package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private int idPregunta;
     private String respuestaCorrecta;
     private String pregunta;
     private String opcionRespuesta1;
     private String opcionRespuesta2;
     private String opcionRespuesta3;
     private String opcionRespuesta4;

    public Preguntas() {
    }

    public Preguntas(int idPregunta, String respuestaCorrecta, String pregunta, String opcionRespuesta1, String opcionRespuesta2, String opcionRespuesta3, String opcionRespuesta4) {
       this.idPregunta = idPregunta;
       this.respuestaCorrecta = respuestaCorrecta;
       this.pregunta = pregunta;
       this.opcionRespuesta1 = opcionRespuesta1;
       this.opcionRespuesta2 = opcionRespuesta2;
       this.opcionRespuesta3 = opcionRespuesta3;
       this.opcionRespuesta4 = opcionRespuesta4;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getRespuestaCorrecta() {
        return this.respuestaCorrecta;
    }
    
    public void setRespuestaCorrecta(String respuestaCorrecta) {
        this.respuestaCorrecta = respuestaCorrecta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getOpcionRespuesta1() {
        return this.opcionRespuesta1;
    }
    
    public void setOpcionRespuesta1(String opcionRespuesta1) {
        this.opcionRespuesta1 = opcionRespuesta1;
    }
    public String getOpcionRespuesta2() {
        return this.opcionRespuesta2;
    }
    
    public void setOpcionRespuesta2(String opcionRespuesta2) {
        this.opcionRespuesta2 = opcionRespuesta2;
    }
    public String getOpcionRespuesta3() {
        return this.opcionRespuesta3;
    }
    
    public void setOpcionRespuesta3(String opcionRespuesta3) {
        this.opcionRespuesta3 = opcionRespuesta3;
    }
    public String getOpcionRespuesta4() {
        return this.opcionRespuesta4;
    }
    
    public void setOpcionRespuesta4(String opcionRespuesta4) {
        this.opcionRespuesta4 = opcionRespuesta4;
    }




}


