package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * RealizanId generated by hbm2java
 */
public class RealizanId  implements java.io.Serializable {


     private int usuariosIdUsuario;
     private int examenFinalIdExamenFinal;

    public RealizanId() {
    }

    public RealizanId(int usuariosIdUsuario, int examenFinalIdExamenFinal) {
       this.usuariosIdUsuario = usuariosIdUsuario;
       this.examenFinalIdExamenFinal = examenFinalIdExamenFinal;
    }
   
    public int getUsuariosIdUsuario() {
        return this.usuariosIdUsuario;
    }
    
    public void setUsuariosIdUsuario(int usuariosIdUsuario) {
        this.usuariosIdUsuario = usuariosIdUsuario;
    }
    public int getExamenFinalIdExamenFinal() {
        return this.examenFinalIdExamenFinal;
    }
    
    public void setExamenFinalIdExamenFinal(int examenFinalIdExamenFinal) {
        this.examenFinalIdExamenFinal = examenFinalIdExamenFinal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RealizanId) ) return false;
		 RealizanId castOther = ( RealizanId ) other; 
         
		 return (this.getUsuariosIdUsuario()==castOther.getUsuariosIdUsuario())
 && (this.getExamenFinalIdExamenFinal()==castOther.getExamenFinalIdExamenFinal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuariosIdUsuario();
         result = 37 * result + this.getExamenFinalIdExamenFinal();
         return result;
   }   


}


