package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Realizan generated by hbm2java
 */
public class Realizan  implements java.io.Serializable {


     private RealizanId id;

    public Realizan() {
    }

    public Realizan(RealizanId id) {
       this.id = id;
    }
   
    public RealizanId getId() {
        return this.id;
    }
    
    public void setId(RealizanId id) {
        this.id = id;
    }




}


