package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Temas generated by hbm2java
 */
public class Temas  implements java.io.Serializable {


     private Integer idTema;
     private String nombre;
     private String descripcion;
     private String puntajeEvaluacion;
     private String puntajePractico;
     private String titulo;
     private String contenido;
     private int tipoTemaIdTipoTema;

    public Temas() {
    }

	
    public Temas(String nombre, String descripcion, int tipoTemaIdTipoTema) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tipoTemaIdTipoTema = tipoTemaIdTipoTema;
    }
    public Temas(String nombre, String descripcion, String puntajeEvaluacion, String puntajePractico, String titulo, String contenido, int tipoTemaIdTipoTema) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.puntajeEvaluacion = puntajeEvaluacion;
       this.puntajePractico = puntajePractico;
       this.titulo = titulo;
       this.contenido = contenido;
       this.tipoTemaIdTipoTema = tipoTemaIdTipoTema;
    }
   
    public Integer getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPuntajeEvaluacion() {
        return this.puntajeEvaluacion;
    }
    
    public void setPuntajeEvaluacion(String puntajeEvaluacion) {
        this.puntajeEvaluacion = puntajeEvaluacion;
    }
    public String getPuntajePractico() {
        return this.puntajePractico;
    }
    
    public void setPuntajePractico(String puntajePractico) {
        this.puntajePractico = puntajePractico;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public int getTipoTemaIdTipoTema() {
        return this.tipoTemaIdTipoTema;
    }
    
    public void setTipoTemaIdTipoTema(int tipoTemaIdTipoTema) {
        this.tipoTemaIdTipoTema = tipoTemaIdTipoTema;
    }




}


