package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * TienenId generated by hbm2java
 */
public class TienenId  implements java.io.Serializable {


     private int temasIdTema;
     private int preguntasIdPregunta;

    public TienenId() {
    }

    public TienenId(int temasIdTema, int preguntasIdPregunta) {
       this.temasIdTema = temasIdTema;
       this.preguntasIdPregunta = preguntasIdPregunta;
    }
   
    public int getTemasIdTema() {
        return this.temasIdTema;
    }
    
    public void setTemasIdTema(int temasIdTema) {
        this.temasIdTema = temasIdTema;
    }
    public int getPreguntasIdPregunta() {
        return this.preguntasIdPregunta;
    }
    
    public void setPreguntasIdPregunta(int preguntasIdPregunta) {
        this.preguntasIdPregunta = preguntasIdPregunta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TienenId) ) return false;
		 TienenId castOther = ( TienenId ) other; 
         
		 return (this.getTemasIdTema()==castOther.getTemasIdTema())
 && (this.getPreguntasIdPregunta()==castOther.getPreguntasIdPregunta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTemasIdTema();
         result = 37 * result + this.getPreguntasIdPregunta();
         return result;
   }   


}


