package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Tienen generated by hbm2java
 */
public class Tienen  implements java.io.Serializable {


     private TienenId id;

    public Tienen() {
    }

    public Tienen(TienenId id) {
       this.id = id;
    }
   
    public TienenId getId() {
        return this.id;
    }
    
    public void setId(TienenId id) {
        this.id = id;
    }




}


