package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * TipoTema generated by hbm2java
 */
public class TipoTema  implements java.io.Serializable {


     private Integer idTipoTema;
     private String tipoTema;

    public TipoTema() {
    }

    public TipoTema(String tipoTema) {
       this.tipoTema = tipoTema;
    }
   
    public Integer getIdTipoTema() {
        return this.idTipoTema;
    }
    
    public void setIdTipoTema(Integer idTipoTema) {
        this.idTipoTema = idTipoTema;
    }
    public String getTipoTema() {
        return this.tipoTema;
    }
    
    public void setTipoTema(String tipoTema) {
        this.tipoTema = tipoTema;
    }




}


