package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Trabajan generated by hbm2java
 */
public class Trabajan  implements java.io.Serializable {


     private TrabajanId id;

    public Trabajan() {
    }

    public Trabajan(TrabajanId id) {
       this.id = id;
    }
   
    public TrabajanId getId() {
        return this.id;
    }
    
    public void setId(TrabajanId id) {
        this.id = id;
    }




}


