package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * TrabajanId generated by hbm2java
 */
public class TrabajanId  implements java.io.Serializable {


     private int usuariosIdUsuario;
     private int temasIdTema;

    public TrabajanId() {
    }

    public TrabajanId(int usuariosIdUsuario, int temasIdTema) {
       this.usuariosIdUsuario = usuariosIdUsuario;
       this.temasIdTema = temasIdTema;
    }
   
    public int getUsuariosIdUsuario() {
        return this.usuariosIdUsuario;
    }
    
    public void setUsuariosIdUsuario(int usuariosIdUsuario) {
        this.usuariosIdUsuario = usuariosIdUsuario;
    }
    public int getTemasIdTema() {
        return this.temasIdTema;
    }
    
    public void setTemasIdTema(int temasIdTema) {
        this.temasIdTema = temasIdTema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrabajanId) ) return false;
		 TrabajanId castOther = ( TrabajanId ) other; 
         
		 return (this.getUsuariosIdUsuario()==castOther.getUsuariosIdUsuario())
 && (this.getTemasIdTema()==castOther.getTemasIdTema());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuariosIdUsuario();
         result = 37 * result + this.getTemasIdTema();
         return result;
   }   


}


