package com.samd.modelo;
// Generated 01-jul-2017 22:47:40 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String apellido;
     private String cedula;
     private String contrasenia;
     private String nroDocente;
     private String estado;
     private int idTipo;

    public Usuarios() {
    }

	
    public Usuarios(String nombre, String apellido, String cedula, String contrasenia, String estado, int idTipo) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.contrasenia = contrasenia;
        this.estado = estado;
        this.idTipo = idTipo;
    }
    public Usuarios(String nombre, String apellido, String cedula, String contrasenia, String nroDocente, String estado, int idTipo) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.contrasenia = contrasenia;
       this.nroDocente = nroDocente;
       this.estado = estado;
       this.idTipo = idTipo;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getNroDocente() {
        return this.nroDocente;
    }
    
    public void setNroDocente(String nroDocente) {
        this.nroDocente = nroDocente;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }




}


